name: Tests

permissions:
  pull-requests: write # Necessary to comment on PRs
  actions: write       # Necessary to cancel workflow executions
  packages: write
  deployments: write
  statuses: write
  contents: write

on:
  pull_request

jobs:
  run-tests:
    runs-on: ubuntu-latest

    services:

      redis: 
        image: redis:8.0-M03
        
        ports:
          - 6379:6379         

      mysql: 
        image: mysql:8.0
        
        ports:
          - 3306:3306

        env:
          MYSQL_DATABASE: laravel
          MYSQL_ALLOW_EMPTY_PASSWORD: yes   

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.1.7

      - name: Setup PHP and Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, gd, redis, igbinary, msgpack, zstd, lz4, memcached, gmp, :php-psr
          tools: composer:v2

      - name: Install Dependencies
        run: composer install -q --no-interaction

      - name: Prep Application
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Run Tests
          
        run: php artisan test --compact