name: Tests

permissions:
  pull-requests: write # Necessary to comment on PRs
  actions: write       # Necessary to cancel workflow executions
  packages: write
  deployments: write
  statuses: write
  contents: write

on:
  pull_request

jobs:
  run-tests:
    runs-on: ubuntu-22.04

    services:

      redis: 
        image: redis:8.0-M03
        
        ports:
          - 6379:6379         

      mysql: 
        image: mysql:8.0
        
        ports:
          - 3306:3306

        env:
          MYSQL_DATABASE: laravel 
          MYSQL_ALLOW_EMPTY_PASSWORD: yes  
          
    env: 
      PHP_VERSION: 8.3
      CACHE_KEY: extensions-cache-v1
      PHP_EXTENSIONS: dom, curl, libxml, mbstring, pcntl, pdo, sqlite, pdo_sqlite, gd, redis, igbinary, msgpack, lzf, zstd, lz4, memcached, gmp, :php-psr

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.1.7 

      - name: Setup
        uses: ./ci/.github/actions/setup    


      - name: Install Dependencies
        run: composer install -q --no-interaction

      - name: Prep Application
        run: |
          cp .env.example .env
          php artisan key:generate
     
      - name: Run Laravel Pint
        run: vendor/bin/pint --test
   
      - name: Run Tests          
        run: php artisan test --compact